### ISSUE TITLE
Missing 'LitJson' 

### ISSUE THREAD

**Issue by hyakugei** [MacacaGames/UnityDocGenerator#1]
Error(s) in the console related to the `LitJson` tool.

`Library/PackageCache/com.macacagames.docgenerator@f77de9aee3/Editor/DocGeneratorWindow.cs(364,38): error CS0103: The name 'LitJson' does not exist in the current context
`

`Library/PackageCache/com.macacagames.docgenerator@f77de9aee3/Editor/DocGeneratorWindow.cs(290,13): error CS0246: The type or namespace name 'LitJson' could not be found (are you missing a using directive or an assembly reference?)
`

**Comment by sableangle** [comment]
Hi start from ver 1.0.1 this plugin is migrate from LitJson to Unity's built-in JsonUtility.

you can change the version number in Packages/manifest.json like this to use the 1.0.1 ver.
"com.macacagames.docgenerator": "https://github.com/MacacaGames/UnityDocGenerator.git#1.0.1"

**Comment by hyakugei** [comment]
Ah great. You should update the main pages install docs as they still suggest the `1.0.0` version.
